"""/api/meta: data window, freshness and dimension metadata.

Dimension values come from their single sources of truth, never from literals
in the API: plan tiers and prices from billing (gold.fct_workspace_mrr),
features from analytics/features.py, experiments from the registry, health
tiers from analytics/health_scoring.py.
"""
from datetime import datetime, timezone

from analytics.features import AI_FEATURES, FEATURE_MAP
from analytics.health_scoring import TIER_BINS, TIER_LABELS
from api import __version__
from api.repositories import meta as repo
from api.repositories import system
from api.schemas.common import Envelope, ResponseMeta
from api.schemas.meta import (Dataset, ExperimentSummary, Feature, HealthTier, MetaData,
                              PipelineRun, PlanTier)
from experimentation.experiments import EXPERIMENTS

DEFINITIONS = 'docs/metric-definitions.md'
SYNTHETIC_CAVEAT = ('The dataset is synthetic: generated by scripts/generate_synthetic_data.py '
                    'for calendar 2025, not real customer data.')


def health_tiers():
    return [HealthTier(label=label, min=TIER_BINS[i], max=TIER_BINS[i + 1])
            for i, label in enumerate(TIER_LABELS)]


def features():
    return [Feature(name=name, is_ai=name in AI_FEATURES)
            for name in sorted(set(FEATURE_MAP.values()))]


def experiments():
    return [ExperimentSummary(experiment_id=e.experiment_id, kind=e.kind,
                              start=e.start, end=e.end)
            for e in sorted(EXPERIMENTS.values(), key=lambda e: e.experiment_id)]


def build(conn, settings):
    data_start, data_end = repo.data_window(conn)
    run = system.last_successful_run(conn)
    synthetic = settings.api_dataset_label == 'synthetic'
    data = MetaData(
        data_start=data_start,
        data_end=data_end,
        health_snapshot_date=repo.health_snapshot_date(conn),
        last_successful_run=PipelineRun(**run) if run else None,
        plan_tiers=[PlanTier(**t) for t in repo.plan_tiers(conn)],
        features=features(),
        experiments=experiments(),
        health_tiers=health_tiers(),
        api_version=__version__,
        dataset=Dataset(label=settings.api_dataset_label, synthetic=synthetic),
    )
    meta = ResponseMeta(
        as_of=data_end, data_start=data_start, data_end=data_end,
        sources=list(repo.SOURCES), data_version=run['run_id'] if run else None,
        generated_at=datetime.now(timezone.utc), definitions=DEFINITIONS,
        caveats=[SYNTHETIC_CAVEAT] if synthetic else [],
    )
    return Envelope[MetaData](data=data, meta=meta)
